version: '3'

tasks:
  generate-proto:
    cmds:
      - echo "Generating gRPC code"
      - mkdir -p gen/go
      - |
        protoc --proto_path=api/ \
               --proto_path=../vendor-proto/googleapis \
               --go_out=gen/go \
               api/kafka/types.proto
    deps:
      - ensure-protoc

  ensure-protoc:
    cmds:
      - |
        if ! command -v protoc &> /dev/null; then
          echo "protoc could not be found, installing it now..."
          mkdir -p /tmp/protoc_install
          curl -Lo /tmp/protoc_install/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v27.3/protoc-27.3-linux-x86_64.zip
          unzip /tmp/protoc_install/protoc.zip -d /usr/local
          rm -rf /tmp/protoc_install
          echo "protoc installed successfully!"
        else
          echo "protoc is already installed"
        fi
      - protoc --version

  download-vendor-protos:
    cmds:
      - echo "Cloning Google APIs repo"
      - mkdir -p vendor-proto
      - git clone https://github.com/googleapis/googleapis.git vendor-proto/googleapis
      - echo "Cloning gRPC-Gateway repo"
      - git clone https://github.com/grpc-ecosystem/grpc-gateway.git vendor-proto/grpc-gateway
    desc: "Clone full Google API and gRPC-Gateway proto repositories"

  clean:
    cmds:
      - echo "Cleaning generated files..."
      - rm -rf gen/go gen/swagger vendor-proto

  add-to-scheme-registry:
    cmds:
      - echo "Adding schema to schema registry"
      - |
        curl -X POST http://localhost:8081/subjects/log_event-values/versions \
        -H "Content-Type: application/vnd.schemaregistry.v1+json" \
        -d '{
        "schemaType": "PROTOBUF",
        "schema": "syntax = \"proto3\"; package kafka.types; import \"google/protobuf/timestamp.proto\"; enum LogLevel { LOG_LEVEL_UNSPECIFIED = 0; LOG_LEVEL_DEBUG = 1; LOG_LEVEL_INFO = 2; LOG_LEVEL_WARNING = 3; LOG_LEVEL_ERROR = 4; LOG_LEVEL_CRITICAL = 5; } message LogEvent { string message = 1; LogLevel level = 2; google.protobuf.Timestamp created_at = 3; }"
        }'
